name: Release

on:
  push:
    tags:
      - "*-v*"

permissions:
  contents: write
  packages: write

env:
  CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

# TODO: Fix all of this
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable

      - name: Install cargo-release
        run: |
          cargo install cargo-release --locked

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Extract package name and version from tag
        id: extract
        run: |
          # Extract package name and version from tag (e.g., v_htmlescape-v0.15.9 -> v_htmlescape, 0.15.9)
          TAG_NAME="${{ github.ref_name }}"
          PACKAGE_NAME=$(echo "$TAG_NAME" | sed 's/-v[0-9].*$//')
          VERSION=$(echo "$TAG_NAME" | sed 's/.*-v//')

          echo "package=$PACKAGE_NAME" >> $GITHUB_OUTPUT
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "tag=$TAG_NAME" >> $GITHUB_OUTPUT

          echo "Package: $PACKAGE_NAME"
          echo "Version: $VERSION"
          echo "Tag: $TAG_NAME"

      - name: Publish to crates.io
        run: |
          # Publish the specific package
          cargo release publish --package ${{ steps.extract.outputs.package }} --execute

      - name: Extract changelog for package
        id: changelog
        uses: mindsers/changelog-reader-action@v2
        with:
          version: ${{ steps.extract.outputs.version }}
          path: CHANGELOG.md
          fallback: "## Changes in ${{ steps.extract.outputs.version }}\n\nSee [CHANGELOG.md](CHANGELOG.md) for detailed changes."

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.extract.outputs.tag }}
          name: "Release ${{ steps.extract.outputs.package }} ${{ steps.extract.outputs.version }}"
          body: |
            ${{ steps.changelog.outputs.clean_changelog }}

            ## Installation

            ```bash
            cargo add ${{ steps.extract.outputs.package }}
            ```
